---
- name: install tomcat server
  hosts: TOMCAT
  become: true

  tasks:
  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre-headless
    become: yes

  - name: download tomcat server packages
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.60/bin//apache-tomcat-9.0.60.tar.gz

      dest: /usr/local
    become: yes

  - name: extract tomcat packages
    unarchive:
      src: /usr/local/apache-tomcat-9.0.60.tar.gz
      dest: /usr/local
      remote_src: yes
    become: yes

  - name: start tomcat services
    shell: nohup /usr/local/apache-tomcat-9.0.60/bin/startup.sh
    become: yes
